name: Delivery CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          cd todo_project
          pip install -r requirements.txt
          pip install pytest bandit

      - name: Executar testes
        run: |
          pytest

      - name: Executar análise SAST com Bandit
        run: |
          bandit -r todo_project

      - name: Executar OWASP Dependency Check
        continue-on-error: true
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Delivery Manager'
          path: './todo_project'
          format: 'HTML'

      - name: Upload relatório Dependency Check
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

      - name: Verificar sintaxe Python
        run: |
          python -m compileall todo_project

  deploy-stage:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Simular Deploy em Ambiente Stage
        run: |
          echo "Aplicação implantada em ambiente Stage"

  dast:

    needs: deploy-stage
    runs-on: ubuntu-latest

    steps:

      - name: Simular Execução do OWASP ZAP
        run: |
          echo "Executando análise DAST"
          echo "OWASP ZAP executado no ambiente Stage"